# Generated by Django 5.0.6 on 2024-08-04 10:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("deleted", "Deleted"),
                ],
                default="created",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="file",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="session",
                to="upload.file",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="hash_serial",
            field=models.CharField(default=uuid.uuid4, max_length=70, unique=True),
        ),
    ]
