# Generated by Django 5.0.6 on 2024-08-04 11:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0002_session_status_alter_session_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="last_used",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
