# Generated by Django 5.0.6 on 2024-08-05 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0004_alter_session_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="files",
                to="upload.filetype",
            ),
        ),
    ]
