# Generated by Django 5.0.6 on 2024-08-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0005_alter_file_file_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="chunked",
            field=models.BooleanField(default=True),
        ),
    ]
