# Generated by Django 5.0.6 on 2024-08-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0006_alter_session_chunked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="file",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="last_used",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
